In [4]:
import pandas as pd
dfp = pd.read_excel("c:/users/change/documents/monthly_production_05-2019.xlsx")
dfr = pd.read_excel("c:/users/change/documents/monthly_revenue_05-2019 (1).xlsx")

In [5]:
dfr.describe()

       Calendar Year       Revenue
count    7179.000000  7.179000e+03
mean     2013.276501  1.837912e+07
std         3.313896  7.662594e+07
min      2008.000000 -6.651556e+08
25%      2010.000000  5.416600e+02
50%      2013.000000  7.949200e+04
75%      2016.000000  6.168047e+06
max      2019.000000  2.882444e+09

In [6]:
pro_vol = dfp["Volume"]
print("Low Range: " + str(pro_vol.mean() - pro_vol.std()))
print("High Range: " + str(pro_vol.mean() + pro_vol.std()))
print(pro_vol.min())
print(pro_vol.max())

Low Range: -27669457.510823295
High Range: 167535213.24741733
701080.0
348465708.66177

In [65]:
g = dfr.groupby(["Commodity"]) 
for c, d in g:
    print("-------\n" + str(c) + "\n-------")
    ind = d.index
    maxs = d["Revenue"].mean() + (d["Revenue"].std() * 3)
    mins = d["Revenue"].mean() - (d["Revenue"].std() * 3)
    
    for i in ind:
        value = dfr.loc[i,"Revenue"]
        if value >= maxs or value <= mins:
            print(i, value, sep=": ")

-------
Asphalt
-------
-------
Clay
-------
3766: -3717.02
3782: -2660.0
-------
Coal
-------
65: 214677491.26
377: 108151619.37
689: 213333780.11
2162: 110189969.6
2625: 105727887.13
2781: 140356636.78
2886: 158694382.16
3503: 158694382.16
4126: 158654062.16
4751: 162826502.16
5398: 158656862.16
-------
Copper
-------
2491: 1766510.25
2541: -951986.05
2904: -514524.2
-------
Garnet
-------
-------
Gas
-------
8: 203870092.1
61: 240128191.28
86: 199452181.169999
112: 265565366.829999
167: 240885671.11
189: 227196940.849999
214: 234394980.49
236: 209804635.82
264: 325978505.21
289: 296523055.939999
319: 322614676.37
344: 289093273.429999
373: 335191977.89
397: 255121770.050001
424: 310549708.980001
450: 328237894.960001
1147: -280791482.12
1379: 198921953.54
-------
Gemstones
-------
-------
Geothermal
-------
482: 24585165.0
1099: 8402869.0
-------
Gilsonite
-------
274: 8508.0
382: 20256.58
644: 10222.8
954: -12255.69
-------
Gold
-------
-------
Gypsum
-------
5141: 320530.07
6459: 371049.46
7113: 408410.3
-------
Hardrock
-------
498: 163855.0
552: -163065.5
1111: 173065.08
1165: -163057.5
1741: 163935.0
1791: -164290.0
2350: 163901.5
2400: -163580.0
2968: 164095.0
3021: -154184.0
3586: 164902.5
3634: -163209.0
-------
Hot Springs
-------
-------
Limestone
-------
5631: 493464.65
-------
Mining-Unspecified
-------
5338: 36220.0
5875: 30015.0
-------
NGL
-------
2253: 35325928.3299999
2258: 33879178.7399999
2514: 34276193.3600001
3085: 75745645.2500004
3853: 36518695.12
-------
Oil
-------
375: 679847822.829999
426: 638140893.61
1149: -665155621.339999
2098: 579805597.019998
2254: 576859794.69
2510: 547871648.42
2667: 622539972.280001
2722: 529110675.360001
3180: 645417061.189998
3286: 591133666.19
3545: 567247415.04
4001: 549882512.899999
4114: 547670492.309999
4166: 523482053.0
4216: 604214772.76
7138: 583574815.52
-------
Oil & Gas
-------
55: 629077931.0
106: 935646488.0
160: 562220074.0
208: 2882444092.0
257: 1896223962.0
313: 747749665.000001
367: 911072998.0
1140: 731098236.0
1561: 604759063.63
2989: 725946155.0
3453: 753565936.6
4013: 714642270.0
4645: 440507112.0
6752: 975938748.0
-------
Oil Shale
-------
1420: 674473.6
1633: -674473.6
-------
Other Products
-------
561: 23694114.3199998
1087: 33052072.34
6642: 23863683.09
-------
Phosphate
-------
2217: 755824.0
2628: 799997.74
-------
Potassium
-------
2218: 19377624.73
-------
Quartz
-------
-------
Sand & Gravel
-------
4560: 489584.25
5200: 405000.0
5213: 454500.0
6015: -932762.58
-------
Silica Sand
-------
-------
Sodium
-------
599: 425693.91
4287: 402000.0
5346: 424121.28
6099: 975000.0
6982: 489000.0
-------
Sulfur
-------
-------
Tar Sands
-------
-------
Wind
-------
7074: 405100000.0

In [60]:
g = dfp.groupby(["Commodity"]) 
for c, d in g:
    print("-------\n" + str(c) + "\n-------")
    ind = d.index
    maxs = d["Volume"].mean() + (d["Volume"].std() * 3)
    mins = d["Volume"].mean() - (d["Volume"].std() * 3)
    
    for i in ind:
        value = dfp.loc[i,"Volume"]
        if value >= maxs or value <= mins:
            print(i, value, sep=": ")

-------
Coal Prod Vol (ton)
-------
-------
Gas Prod Vol (mcf)
-------
-------
Oil Prod Vol (bbl)
-------

In [1]:
import json

In [6]:
class Car:
    __slots__ = ['wheels']
    
    def __init__(self, wheels):
        self.wheels = ['2','2']

hyundai = Car(4)

def encode_car(car):
    return car.wheels

In [7]:
with open("somefile.json", "w") as file:
    json.dump(hyundai, file, indent=2, default=encode_car)

In [8]:
with open("somefile.json", "r") as file:
    print(json.load(file))

['2', '2']